version: '3.8'
services:
  mongo:
    image: mongo
    container_name: reddit_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db #To be replaced with mongo_data:/data/db
      - ./infra/docker/mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
    environment:
      MONGO_INITDB_DATABASE: reddit_scraper
    init: true


  postgres:
    image: postgres
    container_name: reddit_postgres
    environment:
      POSTGRES_USER: topic_watch
      POSTGRES_PASSWORD: RandomPassword123
      POSTGRES_DB: reddit_auth
    ports:
      - "5432:5432"
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data  #To be replaced with : postgres_data:/var/lib/postgresql/data
      - ./infra/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    init: true

volumes:
  mongo_data:  # Volume not used. Bind mount is used instead.
  postgres_data: # Volume not used. Bind mount is used instead. 